# Generated by Django 6.0.5 on 2026-05-22 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom du sport')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text="Classe CSS pour l'icône (ex: fa-futbol)", max_length=50)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin (optionnel)')),
                ('venue_name', models.CharField(max_length=150, verbose_name='Nom du lieu (ex: Stade Ernest-Wallon)')),
                ('city', models.CharField(default='Toulouse', max_length=100, verbose_name='Ville')),
                ('price', models.CharField(blank=True, help_text='Ex: Gratuit, 10€, Prix libre', max_length=50, verbose_name='Prix')),
                ('ticket_link', models.URLField(blank=True, verbose_name='Lien billetterie / Infos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matchfinder.sport')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_time'],
            },
        ),
    ]
