# Generated by Django 6.0.5 on 2026-05-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_api_id',
            field=models.CharField(blank=True, help_text="ID unique de l'événement provenant de l'API", max_length=255, null=True, unique=True),
        ),
    ]
