# Generated by Django 6.0.5 on 2026-06-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchfinder', '0002_event_external_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='league_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Compétition (ex: Ligue 1)'),
        ),
    ]
