# Generated by Django 6.0.5 on 2026-06-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchfinder', '0003_event_league_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='Image du lieu'),
        ),
    ]
